### ISSUE TITLE
Vuelos

### ISSUE THREAD

**Issue by der1003** [cvr1008/practicaSoftware#10]
Planear cuantos vuelos debemos coger y a que precio.

**Comment by PaulaMartinezCamarero** [comment]
yo cogería un vuelo directo a Roma, sin escalas ni nada.

**Comment by PaulaMartinezCamarero** [comment]
![WhatsApp Image 2024-03-11 at 15 42 16](https://github.com/cvr1008/practicaSoftware/assets/162353881/87e5192d-d898-4266-9fef-38dfae63d600)

he encontrado esta oferta, ¿que os parece?
Yo creo que esta muy bien de precio

**Comment by aeu1002** [comment]
Me parece genial. Además yo prefiero ir sin hacer escala.

**Comment by der1003** [comment]
Bien, lo reservaré yo.
