### ISSUE TITLE
Posibles lesiones

### ISSUE THREAD

**Issue by cvr1008** [cvr1008/practicaSoftware#15]
Es importante saber dónde podemos obtener asistencia médica en caso de necesitarla.

**Comment by PaulaMartinezCamarero** [comment]
Me he informado y estos son algunos de los hospitales de Roma:
1. UPMC Salvator Mundi International Hospital
2. Rome Cristo Re Hospital
3. Azienda Ospedaliera San Giovanni Addolorata

**Comment by cvr1008** [comment]
Muchas gracias!!
