### ISSUE TITLE
Destinos a elegir

### ISSUE THREAD

**Issue by der1003** [cvr1008/practicaSoftware#4]
¿Qué destino preferís?
-Viena
-Oslo
-Sofía
-Roma
-Budapest

**Comment by PaulaMartinezCamarero** [comment]
Hola chicos, yo haría lo siguiente: ir al sitio que salga elegido por mayoría, ¿qué os parece?

Mi voto es por Roma.

**Comment by der1003** [comment]
@PaulaMartinezCamarero Que buena idea, me parece bien Roma

**Comment by cvr1008** [comment]
Por mí es perfecto!
Roma y Budapest son mis preferidos.

**Comment by aeu1002** [comment]
Justo mi destino favorito

**Comment by aeu1002** [comment]
Sabía que no me fallaríais

**Comment by PaulaMartinezCamarero** [comment]
¡Perfecto!
Destino elegido, seguro que lo pasamos genial.
